export const INSPECTION_AUDIT_TRAIL_VERSION = "2027.1";

export const APPEND_ONLY_AUDIT_TABLE = "inspection_audit_events";

export const ALLOWED_AUDIT_METADATA_KEYS = new Set([
  "photo_id",
  "file_hash",
  "job_id",
  "observation_id",
  "observation_ids",
  "proposed_count",
  "entries_count",
  "content_hash",
  "change_types",
  "gate",
  "ruleset_id",
  "blocking_count",
  "warning_count",
  "pdf_path_hash",
  "analysis_status",
  "deduplicated",
  "ai_model",
  "prompt_version",
  "feedback_events",
  "action",
  "user_id",
  "organization_id",
  "assignment_id",
  "assigned_to_user_id",
  "assigned_by_user_id",
  "assignment_role",
  "invitation_id",
  "invitation_role",
  "invited_by_user_id",
  "email_hash",
  "member_id",
  "member_role",
  "previous_plan",
  "new_plan",
  "inspector_id",
  "inspector_name",
  "inspector_company",
]);
